Fix wdrc to run at sites with multiple rx888s

diff --git a/bash-aliases b/bash-aliases
--- a/bash-aliases
+++ b/bash-aliases
@@ -118,7 +118,7 @@ function wd-find-kiwis()
 {
     local local_lan_list=( $(ip addr | grep -w inet | grep -v 'inet 127' | awk '{print $2}' | sed 's;\.[0-9]*/;.0/;g') )
 
-    [[ ${verbosity} -gt 0 ]] && echo "Searching the ${#local_lan_list[@]} LANs for Kiwis:  ${local_lan_list[@]}"
+    [[ ${verbosity-0} -gt 0 ]] && echo "Searching the ${#local_lan_list[@]} LANs for Kiwis:  ${local_lan_list[@]}"
     for lan in ${local_lan_list[@]} ; do
         echo "Searching LAN ${lan} for Kiwis"
         local kiwi_ip_list=( $( nmap --open -p 8073 ${lan} | awk '/Nmap scan report for/{print $5}' ) )
@@ -145,19 +145,19 @@ function wd-kiwi-status()
         local rx_name=${rx_fields[0]};
         local rx_ip_port=${rx_fields[1]};
         if [[ ${rx_name} =~ AUDIO* ]] || [[ ${rx_name} =~ MERG* ]] || [[ ${rx_name} =~ RTL* ]]; then
-            [[ ${verbosity} -ge 1 ]] && echo "skipping rx ${rx_name}";
+            [[ ${verbosity-0} -ge 1 ]] && echo "skipping rx ${rx_name}";
         else
             local rx_ip=${rx_ip_port/:*/};
             if ! ping -c 1 -W 1 ${rx_ip} > /dev/null; then
                 echo "WARNING: the Kiwi '${rx_name}' defined in ${wsprconf_file} doesn't respond to pings";
             else
                 kiwi_list+=(${rx_name},${rx_ip_port});
-                [[ ${verbosity} -ge 1 ]] && echo "Added ${rx_name} => ${rx_ip}";
+                [[ ${verbosity-0} -ge 1 ]] && echo "Added ${rx_name} => ${rx_ip}";
             fi;
         fi;
     done;
-    [[ ${verbosity} -ge 1 ]] && echo "kiwi_list[@] => ${kiwi_list[@]}";
-    [[ ${verbosity} -ge 1 ]] && echo;
+    [[ ${verbosity-0} -ge 1 ]] && echo "kiwi_list[@] => ${kiwi_list[@]}";
+    [[ ${verbosity-0} -ge 1 ]] && echo;
     local users;
     local users_max;
     local gps_good;
@@ -173,15 +173,15 @@ function wd-kiwi-status()
         users_max=$(sed -n '/users_max=\(.*\)/s//\1/p' <<< ${kiwi_status});
         channels_total=$((channels_total + users_max));
         gps_good=$(sed -n '/gps_good=\(.*\)/s//\1/p' <<< ${kiwi_status});
-        [[ ${verbosity} -ge 1 ]] && printf "%15s: %d channels, %d users, %2d GPS satellites tracked\n" "${kiwi_name}" "${users_max}" "${users}" "${gps_good}";
+        [[ ${verbosity-0} -ge 1 ]] && printf "%15s: %d channels, %d users, %2d GPS satellites tracked\n" "${kiwi_name}" "${users_max}" "${users}" "${gps_good}";
         curl -s http://${kiwi_ip}/users | sed -n 's/"i":\([0-9]*\)/\n\1/g ; s/},{//g ; p' | sed '/\[{/d; s/}]//; s/,/     /g' > /tmp/curl.log;
         while read user_line; do
-            [[ ${verbosity} -ge 1 ]] && echo "Checking '${user_line:1}' on user line ${user_line}"
+            [[ ${verbosity-0} -ge 1 ]] && echo "Checking '${user_line:1}' on user line ${user_line}"
             if grep --color=auto -q wsprdaemon <<< "${user_line}"; then
-                [[ ${verbosity} -ge 1 ]] && echo "skipping WD user";
+                [[ ${verbosity-0} -ge 1 ]] && echo "skipping WD user";
                 wsprdaemon_total=$((wsprdaemon_total + 1));
             else
-                [[ ${verbosity} -ge 1 ]] && echo "Checking '${user_line:1}' on user line ${user_line}"
+                [[ ${verbosity-0} -ge 1 ]] && echo "Checking '${user_line:1}' on user line ${user_line}"
                 if [[ -n "${user_line:1}" ]]; then
                     eval declare $(echo "${user_line:1}" | sed '/"\([^"]*\)":/s//\1=/g');
                     [[ $? -ne 0 ]] && continue
@@ -383,19 +383,19 @@ function kiwi-stats(){
         local rx_name=${rx_fields[0]}
         local rx_ip_port=${rx_fields[1]}
         if [[ ${rx_name} =~ AUDIO* ]] || [[ ${rx_name} =~ MERG* ]] || [[ ${rx_name} =~ RTL* ]] ; then
-            [[ ${verbosity} -ge 1 ]] && echo "skipping rx ${rx_name}"
+            [[ ${verbosity-0} -ge 1 ]] && echo "skipping rx ${rx_name}"
         else
             local rx_ip=${rx_ip_port/:*/}
             if ! ping -c 1 -W 1 ${rx_ip} > /dev/null ; then
                 echo "WARNING: the Kiwi '${rx_name}' defined in ${wsprconf_file} doesn't respond to pings"
             else
                 kiwi_list+=(${rx_name},${rx_ip_port})
-                [[ ${verbosity} -ge 1 ]] && echo "Added ${rx_name} => ${rx_ip}"
+                [[ ${verbosity-0} -ge 1 ]] && echo "Added ${rx_name} => ${rx_ip}"
             fi
         fi
     done
-    [[ ${verbosity} -ge 1 ]] && echo "kiwi_list[@] => ${kiwi_list[@]}"
-    [[ ${verbosity} -ge 1 ]] && echo
+    [[ ${verbosity-0} -ge 1 ]] && echo "kiwi_list[@] => ${kiwi_list[@]}"
+    [[ ${verbosity-0} -ge 1 ]] && echo
 
     local users
     local users_max
@@ -411,7 +411,7 @@ function kiwi-stats(){
         users_max=$(sed -n '/users_max=\(.*\)/s//\1/p' <<< ${kiwi_status})
         channels_total=$((channels_total + users_max))
         gps_good=$(sed -n '/gps_good=\(.*\)/s//\1/p' <<< ${kiwi_status})
-        [[ ${verbosity} -ge 1 ]] && printf "%15s: %d channels, %d users, %2d GPS satellites tracked\n" "${kiwi_name}" "${users_max}" "${users}" "${gps_good}"
+        [[ ${verbosity-0} -ge 1 ]] && printf "%15s: %d channels, %d users, %2d GPS satellites tracked\n" "${kiwi_name}" "${users_max}" "${users}" "${gps_good}"
 
         ### I was unable to parse the curl output when it was assigned to a bash variable. After some frustration I am using the hack of
         ### piping curl's output to a /tmp file and reading and parsing it from there
@@ -419,7 +419,7 @@ function kiwi-stats(){
         curl -s http://${kiwi_ip}/users | sed -n 's/"i":\([0-9]*\)/\n\1/g ; s/},{//g ; p' | sed '/\[{/d; s/}]//; s/,/     /g' > /tmp/curl.log
         while read user_line; do
             if grep -q wsprdaemon <<< "${user_line}" ; then
-                [[ ${verbosity} -ge 1 ]] && echo "skipping WD user"
+                [[ ${verbosity-0} -ge 1 ]] && echo "skipping WD user"
                 wsprdaemon_total=$((wsprdaemon_total + 1))
             else
                 if [[ -n "${user_line:1}" ]]; then
@@ -462,7 +462,6 @@ function wd-merged() {
     echo "Found ${#merged_file_list[@]} 'merged.log' files:"
     local i
     for  (( i = 0; i < ${merged_file_count}; ++i )); do
-        #set -x
         local file_line_list=( $(ls -l ${merged_file_list[${i}]}) )
         local merge_log_line_count=$( wc -l < ${merged_file_list[${i}]} )
         printf "%2d:  %-70s %s %2s %s %6s bytes = %4d lines\n" ${i} ${file_line_list[-1]} ${file_line_list[-4]}  ${file_line_list[-3]}  ${file_line_list[-2]}  ${file_line_list[-5]} ${merge_log_line_count}
@@ -648,7 +647,6 @@ comment_out
            kiwi_root_path="/${kiwi_root_path// /\/}"
            #echo "kiwi_root_path = ${kiwi_root_path}"
            kiwi_root_path_list+=(${kiwi_root_path})
-           set +x
            #read -p "Next Kiwi path => "
         fi
     done
@@ -774,7 +772,23 @@ function wd-wavs() {
 ###
 function wd-get_ka9q-conf_file-base_name() {
     source ~/wsprdaemon/wsprdaemon.conf
-    local conf_base_name=${KA9Q_CONF_NAME:-rx888-wsprdaemon}
+    local conf_base_name
+
+    if [[ -n "${KA9Q_CONF_NAME-}" ]]; then
+        [[ ${verbosity-0} -gt 0 ]] && echo "Using conf base name KA9Q_CONF_NAME='${KA9Q_CONF_NAME}' found in  ~/wsprdaemon/wsprdaemon.conf" 1>&2
+        conf_base_name="${KA9Q_CONF_NAME}"
+    else
+        [[ ${verbosity-0} -gt 0 ]] && echo "Using default conf base name 'rx888-wsprsdaemon'" 1>&2
+         conf_base_name="rx888-wsprdaemon"
+    fi
+
+    local running_radiod_status_line_list=( $(sudo systemctl | grep radiod@) )
+    if [[ ${#running_radiod_status_line_list[@]} -gt 0 ]]; then
+        local radiod_service_name="${running_radiod_status_line_list[0]}"
+        conf_base_name="${radiod_service_name##*@}"
+        conf_base_name="${conf_base_name%.service}"
+        [[ ${verbosity-0} -gt 0 ]] && echo "Found radiod service:  ${radiod_service_name} and extracted from it the base name ${conf_base_name}" 2>&1
+    fi
     echo "${conf_base_name}"
 }
 
@@ -935,17 +949,22 @@ function wd-radiod-control()
     local mc_url
 
     local radiod_conf_base_name=$(wd-get_ka9q-conf_file-base_name)
-    if [[ "${radiod_conf_base_name}" == "rx888-wsprdaemon" ]]; then
-        mc_url="hf.local"
+    local radio_conf_file_name="/etc/radio/radiod@${radiod_conf_base_name}.conf"
+
+    if [[ ! -f "${radio_conf_file_name}" ]]; then
+        echo "Can't find the radiod configuration file '${radio_conf_file_name}'"
+        return 1
     else
-        if [[ -z "${2-}" ]]; then
-            mc_url="hf-${radiod_conf_base_name}-status.local"
+        local wspr_section_data_url="$(grep -i -A 20 '^\[.*wspr' "${radio_conf_file_name}" | grep "^data" | head -1 | cut -d ' ' -f 3)"
+        if [[ -z "${wspr_section_data_url}" ]]; then
+            echo "Can't find [wspr] data = URL in '${radio_conf_file_name}'"
+            return 2
         else
-            mc_url="hf-${2}-status.local"
+            echo "Found [wspr] data = ${wspr_section_data_url} in '${radio_conf_file_name}'"
+            control -s ${tuning_freq} ${wspr_section_data_url}
         fi
     fi
-
-    control -s ${tuning_freq} ${mc_url}
+    return 0
 }
 alias wd9c=wd-radiod-control
 alias wdrc=wd-radiod-control
@@ -978,13 +997,11 @@ alias wd9m=wd-9m
 
 ### tmux alias
 function tm() {
-    # set -x
     local tm_arg=${1-}
     local tm_list=( $(tmux ls 2> /dev/null | awk -F : '{print $1}') )
     local tm_list_count=${#tm_list[@]}
 
     if [[ -z "${tm_arg}" ]]; then
-        #set +x && return
         if [[ ${tm_list_count} -eq 0 ]]; then
             tmux
             return 0
