Refine  wd-sftp-psws()

diff --git a/bash-aliases b/bash-aliases
--- a/bash-aliases
+++ b/bash-aliases
@@ -1897,33 +1897,53 @@ function wd-sftp-psws(){
         echo "GRAPE_PSWS_ID='${GRAPE_PSWS_ID}' does not match the expected format 'Snnnn_nnn'"
         return 0
     fi
+    local tmpfile=$(mktemp)
+    trap "rm -f '$tmpfile'" RETURN  # cleanup 
+
     local psws_url="${PSWS_URL-pswsnetwork.eng.ua.edu}"
 
     local nc_timeout=${PSWS_NC_TIMEOPUT_SECONDS-2}
     echo "Testing Internnet connectivity to the PSWS server by running 'nc -vz -w ${nc_timeout} ${psws_url} 22'"
     start_epoch=${EPOCHSECONDS}
-    nc -vz -w ${nc_timeout} ${psws_url} 22
+    nc -vz -w ${nc_timeout} ${psws_url} 22 >& ${tmpfile}
     rc=$?
     end_epoch=${EPOCHSECONDS}
     runtime_seconds=$(( end_epoch - start_epoch ))
     if (( rc )); then
-        printf "After %2d seconds, Failed to run 'nc -vz -w ${psws_url} 22' => ${rc}\n" "${runtime_seconds}"
+        printf "After %2d seconds, Failed to run 'nc -vz -w ${psws_url} 22' => ${rc}:\n$(< ${tmpfile} )\n" "${runtime_seconds}" 
+        rm -f ${tmpfile}
         return 1
     fi
     printf "After %2d seconds, Successfully ran 'nc -vz ${psws_url} 22'\n" "${runtime_seconds}"
 
+    if [[ ! -d ~/.ssh ]]; then
+        printf "The ~/.ssh directory which contains ssh keys doesn't exist.  Run 'ssh-keygen -t 25519 -N '' to create them"
+        rm -f ${tmpfile}
+        return 1
+    fi
+    local public_key_file_path_list=( $( find ~/.ssh -name '*.pub') )
+    if (( ${#public_key_file_path_list[@]} == 0 )); then
+        printf "This station ${GRAPE_PSWS_ID%_*} has no ssh public key.  Run 'ssh-keygen -t 25519 -N \"\"' to create it\n"
+        rm -f ${tmpfile}
+        return 1
+    fi
+    local public_key_file_path="${public_key_file_path_list[0]}"
+    (( ${verbosity-0} )) && printf "This station ${GRAPE_PSWS_ID%_*}'s public key is:\n $(< ${public_key_file_path})\n" 
+
     local psws_timeout=$(( nc_timeout * 10 ))    ### Default is to wait up to 20 seconds to execute a simple sftp connection to the PSWS server
     echo "Testing sftp autologin with 'sftp -o ConnectTimeout=${psws_timeout} -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'"
     local start_epoch=${EPOCHSECONDS}
-    sftp -o ConnectTimeout=${psws_timeout} -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}
-    local rc=$? 
-    local end_epoch=${EPOCHSECONDS}
-    local runtime_seconds=$(( end_epoch - start_epoch ))
-    if (( rc )); then
-        printf "After %2d seconds, Failed to run 'sftp -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'\n" "${runtime_seconds}"
+    sftp -o ConnectTimeout=${psws_timeout} -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url} >& ${tmpfile}
+    rc=$? 
+    end_epoch=${EPOCHSECONDS}
+    runtime_seconds=$(( end_epoch - start_epoch ))
+    if (( rc == 0 )); then
+        printf "After %2d seconds, Successfully ran 'sftp -o ConnectTimeout=${psws_timeout} -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'\n" "${runtime_seconds}"
     else
-        printf "After %2d seconds, Successfully ran 'sftp -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'\n" "${runtime_seconds}"
+        printf "After %2d seconds, the Internet connection is open, but failed to run 'sftp -o ConnectTimeout=${psws_timeout} -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}' => ${rc}:\n$(< ${tmpfile} )\n"
+        printf "Verify that this station '${GRAPE_PSWS_ID%_*}'s public key has been registered with the PSWS server:\n $(< ${public_key_file_path})\n"
     fi
+    rm -f ${tmpfile}
     return 0
 }
 alias wdssp=wd-sftp-psws
