Add wd-sftp-psws() which tests access to the HamSCI PSWS server

diff --git a/bash-aliases b/bash-aliases
--- a/bash-aliases
+++ b/bash-aliases
@@ -1882,7 +1882,7 @@ function wd-wav-archive-fix(){
     done
 }
 
-function wd-ssh-psws(){
+function wd-sftp-psws(){
     source ~/wsprdaemon/wsprdaemon.conf
     if [[ -z "${GRAPE_PSWS_ID-}" ]]; then
         echo "This server is not configured with a GRAPE_PSWS_ID in the wsprdaemon.conf file, so can't fix the directories"
@@ -1893,16 +1893,20 @@ function wd-ssh-psws(){
         return 0
     fi
     local psws_url="${PSWS_URL-pswsnetwork.eng.ua.edu}"
-    wd_logger 1 "Executing: 'sftp -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'"
+    echo "Executing: 'sftp -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'"
+    local start_epoch=${EPOCHSECONDS}
     sftp -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}
-    local rc=$? ; if (( rc )); then
-        wd_logger 1 "Failed to run 'sftp -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'"
+    local rc=$? 
+    local end_epoch=${EPOCHSECONDS}
+    local runtime_seconds=$(( end_epoch - start_epoch ))
+    if (( rc )); then
+        printf "After %2d seconds, Failed to run 'sftp -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'\n" "${runtime_seconds}"
     else
-        wd_logger 1 "Successfully ran 'sftp -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'"
+        printf "After %2d seconds, Successfully ran 'sftp -b /dev/null ${GRAPE_PSWS_ID%_*}@${psws_url}'\n" "${runtime_seconds}"
     fi
     return 0
 }
-alias wdssp=wd-ssh-psws
+alias wdssp=wd-sftp-psws
 
 function wd-overloads()
 {
